services:
  - type: web
    name: safetalk-sms-service
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      # Add your environment variables in Render dashboard:
      # SUPABASE_URL, SUPABASE_SERVICE_KEY, OPENAI_API_KEY, etc.